// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"time"

	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"lang.pkg/ent/predicate"
	"lang.pkg/ent/voca"
)

// VocaUpdate is the builder for updating Voca entities.
type VocaUpdate struct {
	config
	hooks      []Hook
	mutation   *VocaMutation
	predicates []predicate.Voca
}

// Where adds a new predicate for the builder.
func (vu *VocaUpdate) Where(ps ...predicate.Voca) *VocaUpdate {
	vu.predicates = append(vu.predicates, ps...)
	return vu
}

// SetKey sets the key field.
func (vu *VocaUpdate) SetKey(s string) *VocaUpdate {
	vu.mutation.SetKey(s)
	return vu
}

// SetValue sets the value field.
func (vu *VocaUpdate) SetValue(s string) *VocaUpdate {
	vu.mutation.SetValue(s)
	return vu
}

// SetExample sets the example field.
func (vu *VocaUpdate) SetExample(s string) *VocaUpdate {
	vu.mutation.SetExample(s)
	return vu
}

// SetCreatedAt sets the created_at field.
func (vu *VocaUpdate) SetCreatedAt(t time.Time) *VocaUpdate {
	vu.mutation.SetCreatedAt(t)
	return vu
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (vu *VocaUpdate) SetNillableCreatedAt(t *time.Time) *VocaUpdate {
	if t != nil {
		vu.SetCreatedAt(*t)
	}
	return vu
}

// Mutation returns the VocaMutation object of the builder.
func (vu *VocaUpdate) Mutation() *VocaMutation {
	return vu.mutation
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (vu *VocaUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(vu.hooks) == 0 {
		affected, err = vu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VocaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vu.mutation = mutation
			affected, err = vu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(vu.hooks) - 1; i >= 0; i-- {
			mut = vu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (vu *VocaUpdate) SaveX(ctx context.Context) int {
	affected, err := vu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (vu *VocaUpdate) Exec(ctx context.Context) error {
	_, err := vu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vu *VocaUpdate) ExecX(ctx context.Context) {
	if err := vu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vu *VocaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   voca.Table,
			Columns: voca.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: voca.FieldID,
			},
		},
	}
	if ps := vu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := vu.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voca.FieldKey,
		})
	}
	if value, ok := vu.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voca.FieldValue,
		})
	}
	if value, ok := vu.mutation.Example(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voca.FieldExample,
		})
	}
	if value, ok := vu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: voca.FieldCreatedAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, vu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voca.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// VocaUpdateOne is the builder for updating a single Voca entity.
type VocaUpdateOne struct {
	config
	hooks    []Hook
	mutation *VocaMutation
}

// SetKey sets the key field.
func (vuo *VocaUpdateOne) SetKey(s string) *VocaUpdateOne {
	vuo.mutation.SetKey(s)
	return vuo
}

// SetValue sets the value field.
func (vuo *VocaUpdateOne) SetValue(s string) *VocaUpdateOne {
	vuo.mutation.SetValue(s)
	return vuo
}

// SetExample sets the example field.
func (vuo *VocaUpdateOne) SetExample(s string) *VocaUpdateOne {
	vuo.mutation.SetExample(s)
	return vuo
}

// SetCreatedAt sets the created_at field.
func (vuo *VocaUpdateOne) SetCreatedAt(t time.Time) *VocaUpdateOne {
	vuo.mutation.SetCreatedAt(t)
	return vuo
}

// SetNillableCreatedAt sets the created_at field if the given value is not nil.
func (vuo *VocaUpdateOne) SetNillableCreatedAt(t *time.Time) *VocaUpdateOne {
	if t != nil {
		vuo.SetCreatedAt(*t)
	}
	return vuo
}

// Mutation returns the VocaMutation object of the builder.
func (vuo *VocaUpdateOne) Mutation() *VocaMutation {
	return vuo.mutation
}

// Save executes the query and returns the updated entity.
func (vuo *VocaUpdateOne) Save(ctx context.Context) (*Voca, error) {
	var (
		err  error
		node *Voca
	)
	if len(vuo.hooks) == 0 {
		node, err = vuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*VocaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			vuo.mutation = mutation
			node, err = vuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(vuo.hooks) - 1; i >= 0; i-- {
			mut = vuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, vuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (vuo *VocaUpdateOne) SaveX(ctx context.Context) *Voca {
	node, err := vuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (vuo *VocaUpdateOne) Exec(ctx context.Context) error {
	_, err := vuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (vuo *VocaUpdateOne) ExecX(ctx context.Context) {
	if err := vuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (vuo *VocaUpdateOne) sqlSave(ctx context.Context) (_node *Voca, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   voca.Table,
			Columns: voca.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: voca.FieldID,
			},
		},
	}
	id, ok := vuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Voca.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := vuo.mutation.Key(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voca.FieldKey,
		})
	}
	if value, ok := vuo.mutation.Value(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voca.FieldValue,
		})
	}
	if value, ok := vuo.mutation.Example(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: voca.FieldExample,
		})
	}
	if value, ok := vuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: voca.FieldCreatedAt,
		})
	}
	_node = &Voca{config: vuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues()
	if err = sqlgraph.UpdateNode(ctx, vuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{voca.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
