// Code generated by entc, DO NOT EDIT.

package book

import (
	"time"
)

const (
	// Label holds the string label denoting the book type in the database.
	Label = "book"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBookID holds the string denoting the book_id field in the database.
	FieldBookID = "book_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPublic holds the string denoting the public field in the database.
	FieldPublic = "public"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// EdgeVocas holds the string denoting the vocas edge name in mutations.
	EdgeVocas = "vocas"

	// Table holds the table name of the book in the database.
	Table = "books"
	// VocasTable is the table the holds the vocas relation/edge.
	VocasTable = "vocas"
	// VocasInverseTable is the table name for the Voca entity.
	// It exists in this package in order to avoid circular dependency with the "voca" package.
	VocasInverseTable = "vocas"
	// VocasColumn is the table column denoting the vocas relation/edge.
	VocasColumn = "book_vocas"
)

// Columns holds all SQL columns for book fields.
var Columns = []string{
	FieldID,
	FieldBookID,
	FieldTitle,
	FieldDescription,
	FieldPublic,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
)
