// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Voca is the predicate function for voca builders.
type Voca func(*sql.Selector)
